export default {
  SUCCESS: 1,
  FAIL: 0,
  OK: "OK",
  ASC: "asc",
  DESC: "desc",
  DEL_FLAG: "del_flag",
  CREATE_DATE: "create_date",
  CREATE_TIME: "create_time",
  SQL_FILTER: "sqlFilter",
  PAGE: "page",
  LIMIT: "limit",
  TOTAL: 'total',
  ORDER_FIELD: "orderField",
  ORDER: "order",
  STR_MONTH: "month",
  STR_DAY: "day",
  DATE_TIME: "yyyy-MM-dd HH:mm:ss",
  DATE_TIME_CODE: "yyyyMMddHHmmss",
};
